version: "3.4"

services:
  grocy:
    image: lscr.io/linuxserver/grocy:latest
    container_name: grocy
    environment:
      PGID: 1000
      PUID: 1003
      UMASK: 002
      TZ: America/New_York
    volumes:
      - /share/CACHEDEV1_DATA/appdata/grocy:/config
    ports:
      - 9283:80
    restart: unless-stopped
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo_db:/data/db

  backend:
    image: ghcr.io/georgegebbett/recipe-buddy-backend:latest
    depends_on:
      - "mongo"

  frontend:
    image: ghcr.io/georgegebbett/recipe-buddy-frontend:latest
    ports:
      - "4000:80"
    depends_on:
      - "backend"

volumes:
  mongo_db:
